/**
 * Bundle the MCP Apps view (mcp-app.html + src/mcp-app-view.ts) into a
 * single self-contained HTML file with Bun's standalone-HTML bundler, then
 * embed it as a TS module so the server (and its tests) can serve the shell
 * without filesystem lookups. Run via `bun run build`.
 */
const bundled = await Bun.build({
  entrypoints: ['./mcp-app.html'],
  outdir: './bin',
  target: 'browser',
  compile: true,
  minify: true,
})

if (!bundled.success) {
  console.error('view bundle failed:', bundled.logs)
  process.exit(1)
}

const html = await Bun.file('bin/mcp-app.html').text()
await Bun.write(
  'src/generated/view-html.ts',
  `// Generated by scripts/embed-view.ts from mcp-app.html — do not edit.\n` +
    `// Rebuild with \`bun run build\` after changing the view.\n` +
    `export default ${JSON.stringify(html)}\n`,
)
console.log(`embedded view shell: ${html.length} bytes -> src/generated/view-html.ts`)
